const experienceEntries = [
  {
    id: 0,
    title: "Senior Software Engineer",
    company: "Launch Darkly",
    duration: "Jan 2025 - Sepetember 2025",
    description: `Worked across multiple teams and features delivering critical user focused deliverables that empowered users to release code to production with the highest level of safety using our Release Guardian platform. Spearheaded frontend development of Highlight monitoring acquisition for implementation into release guardian workflow for users to understand exactly where performance bottlenecks and errors were happening in their deployments.`,
    techStack: [
      { name: "React", src: "/react-icon.png" },
      { name: "Typescript", src: "/typescript-icon.png" },
      { name: "Apollo", src: "/apollo-icon.png" },
      { name: "Vite", src: "/vite-dev-icon.png" },
      { name: "GraphQL", src: "/graphql-logo.png" },
      { name: "Golang", src: "/golang-icon.png" },
      { name: "Github", src: "/github-icon.png" },
      { name: "Jira", src: "/jira-icon.png" },
      { name: "Confluence", src: "/confluence-icon.png" },
    ],
  },
  {
    id: 1,
    title: "Staff Software Engineer",
    company: "Elevance Health",
    duration: "2022 - 2026",
    description: `I have led technical direction for teams across many different platforms consisting of engineers, designers, and business management personnel to create effective healthcare management platforms for doctors to easily and safely manage their patient’s health and prescriptions. I led technical architecture decision making for our offshore teams with regard to software testing, security, container configurations, frontend framework, and internal API systems.`,
    techStack: [
      { name: "Next.js", src: "/nextjs-icon.png" },
      { name: "React", src: "/react-icon.png" },
      { name: "Typescript", src: "/typescript-icon.png" },
      { name: "Angular", src: "/angular-icon.png" },
      { name: "BitBucket", src: "/bitbucket-icon.png" },
      { name: "Docker", src: "/docker-icon.png" },
      { name: "AWS", src: "/aws-icon.png" },
      { name: "Node.js", src: "/node-js-icon.png" },
      { name: "Jira", src: "/jira-icon.png" },
    ],
  },
  {
    id: 2,
    title: "Senior Frontend Engineer",
    company: "Bioplus Rx",
    duration: "2018-2022",
    description: `I was integral in the teams behind both of our Enterprise software platforms, one with a massive variety of medical micro-services spanning the entire organization and the other built on the most modern technologies to serve our patients directly. My work contributed to the sale of our company to Elevance Health to the tune of $1 billion. Here I made high impact decisions on system architecture when we were fleshing out new micro-services and implementing new technologies.`,
    techStack: [
      { name: "Next.js", src: "/nextjs-icon.png" },
      { name: "React", src: "/react-icon.png" },
      { name: "Javascript", src: "/javascript-icon.png" },
      { name: "Redux Toolkit", src: "/redux-icon.png" },
      { name: "Azure", src: "/azure-icon.png" },
      { name: "Swagger", src: "/swagger-api-icon.png" },
    ],
  },
  {
    id: 3,
    title: "Software Engineer",
    company: "VMware",
    duration: "2017 - 2018",
    description: `Developed software applications for use on the battlefield forts in an effort to systematize munitions storage that resulted in eliminating casualties from improper storage procedures in the combat theater. Also consulted Wells Fargo Software teams to improve their performance and availability to their massive customer base. `,
    techStack: [
      { name: "React", src: "/react-icon.png" },
      { name: "Angular", src: "/angular-icon.png" },
      { name: "Java", src: "/java-icon.png" },
      { name: "Jira", src: "/jira-icon.png" },
    ],
  },
];

export default experienceEntries;
